### ISSUE TITLE
MongoError: The dollar ($) prefixed field '$setOnInsert' in '$setOnInsert' is not valid for storage.

### ISSUE THREAD

**Issue by mafzst** [fongandrew/meteor-find-and-modify#15]
Hi!

I'm trying to use your package but I experiencing an issue.

Here my function call:

``` javascript
sections.forEach(s => {
  const localId = s.localId;
  const promise = Sections.findAndModify({
    query: {_id: s._id},
    update: s,
    upsert: true
   });
});
```

An here the stack tracer of the error:

```
Exception while invoking method 'sections.update' MongoError: The dollar ($) prefixed field '$setOnInsert' in '$setOnInsert' is not valid for storage.
     at Object.Future.wait (/home/nicolas/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
     at packages/meteor/helpers.js:119:1
     at [object Object].Mongo.Collection.findAndModify (packages/fongandrew_find-and-modify/find_and_modify.js:54:1)
     at imports/api/sections/methods.js:12:34
     at Array.forEach (native)
     at imports/api/sections/methods.js:10:16
     at [object Object].sectionsUpdate (imports/api/sections/methods.js:7:12)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
     at packages/ddp-server/livedata_server.js:711:19
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     - - - - -
     at Function.MongoError.create (/home/nicolas/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
     at /home/nicolas/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:439:41
     at authenticateStragglers (/home/nicolas/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:399:16)
     at [object Object].messageHandler (/home/nicolas/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:421:5)
     at Socket.<anonymous> (/home/nicolas/.meteor/packages/npm-mongo/.1.5.45.2ipaca++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:294:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

I'm using Meteor `1.4.1` and mongo `2.4.10` and plugin version `0.2.2`.

Thanks for your help

**Comment by fongandrew** [comment]
What does `sections` look like?

**Comment by mafzst** [comment]
Here the content of my `sections` variable (just befor forEach)
``` json
[
   {
      "_id":"XsjnYHKNNBEhYux9s",
      "siteId":"vR7w47x87gJLwyuxg",
      "pageId":"4HMiMy9EhCsCuf97a",
      "title":"Bandeau du site",
      "order":1
   },
   {
      "_id":"bGwA8gbC5Jn4Zswjm",
      "siteId":"vR7w47x87gJLwyuxg",
      "pageId":"4HMiMy9EhCsCuf97a",
      "title":"Première section",
      "background":"#424242",
      "order":13
   },
   {
      "_id":"m6eG29jdTiie4vPyk",
      "siteId":"vR7w47x87gJLwyuxg",
      "pageId":"4HMiMy9EhCsCuf97a",
      "title":"Deuxième section",
      "background":"#424242",
      "order":14
   },
   {
      "_id":"zBoHygjqW5JRWJw2S",
      "siteId":"vR7w47x87gJLwyuxg",
      "pageId":"uchJL6FeCmpEJbACK",
      "title":"Bandeau du site",
      "fullWidth":true,
      "order":1
   },
   {
      "_id":"gCBM8Fzwnif295S3Z",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":2,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"EGcmvikYSFw3DKRaR",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":2,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"dxTCNzMpmExiGtfs6",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":3,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"XmF4MnxFjuBSqkwtR",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":3,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"uvtmpduFbAYcjaMKx",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":4,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"6PLGFNNQTQDgkCZL5",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":4,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"3Haa2KdGcYugX72R4",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":5,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"f3dmnXmG9dHQLGYCg",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":6,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"Yjf294cKpd2mzzj8L",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":7,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"aBnQoXWCx98h87ktx",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":8,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"rAWoDWNRcdedpq5Kf",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":9,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"HHAMvRobzxCWCFS7K",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":10,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"YzYESxbmYL87itTog",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":11,
      "siteId":"vR7w47x87gJLwyuxg"
   },
   {
      "_id":"Qi5eQwk839CvFbqT5",
      "pageId":"4HMiMy9EhCsCuf97a",
      "order":12,
      "siteId":"vR7w47x87gJLwyuxg"
   }
]
```

**Comment by fongandrew** [comment]
OK, try specifying an action or operator of some kind.  Like, try this:

```
sections.forEach(s => {
  const localId = s.localId;
  const promise = Sections.findAndModify({
    query: {_id: s._id},
    update: {$set: s},
    upsert: true
   });
});
```

**Comment by mafzst** [comment]
Hi!

I've tried it but I've encounter another error: `MongoError: After applying the update to the document {_id: null , ...}, the (immutable) field '_id' was found to have been altered to _id: "SoinPjTLGB6rrWDFZ"`

**Comment by fongandrew** [comment]
As the error message suggests,you're trying to update the `_id` attribute. Try passing only the variables you want to update to the `$set` command -- e.g. you basically want to be calling something like this:

```
Sections.findAndModify({
  query: {_id: <some_id>},

  // No _id in update
  update: {$set: {
    pageId: ...,
    order: ...,
    siteId: ...
  }},

  upsert: true
});
```

Because `upsert` is set to true, it should automatically create the object you're querying if it's not found. Alternatively, if you're still running into issues, you may have to add something like `$setOnInsert: {_id: <id>}` to the `update` field.

**Comment by mafzst** [comment]
Thanks a lot, it's works!
